order:
    pattern:  /
    defaults: { _controller: "CoreShopBundle:Order:index" }

order_show:
    pattern:  /{id}/show
    defaults: { _controller: "CoreShopBundle:Order:show" }

order_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CoreShopBundle:Order:edit" }

order_update:
    pattern:  /{id}/update
    defaults: { _controller: "CoreShopBundle:Order:update" }
    requirements: { _method: post }

order_edit_invoice:
    pattern:  /{id}/editinvoice
    defaults: { _controller: "CoreShopBundle:Order:editInvoice" }

order_update_invoice:
    pattern:  /{id}/updateinvoice
    defaults: { _controller: "CoreShopBundle:Order:updateInvoice" }
    requirements: { _method: post }

order_pdfadmin:
    pattern:  /{id}/pdf
    defaults: { _controller: "CoreShopBundle:Order:pdf", checkUser:false }

order_process:
    pattern:  /process
    defaults: { _controller: "CoreShopBundle:Order:process"}
    requirements: { _method: post }
