parameters:
#    core_user_text.example.class: Core\UserTextBundle\Example

services:
#    core_user_text.example:
#        class: %core_user_text.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
