parameters:
#    core_attribute.example.class: Core\AttributeBundle\Example

services:
#    core_attribute.example:
#        class: %core_attribute.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
