parameters:
#    site_content.example.class: Site\ContentBundle\Example

services:
#    site_content.example:
#        class: %site_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
