<?php

namespace Core\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PriceGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceGroupRepository extends EntityRepository
{
    public function updateDefaultPriceGroup($priceGroupId)
    {
        $q = $this->getEntityManager()->createQueryBuilder()
               ->update("CoreUserBundle:PriceGroup", "pg")
               ->set("pg.default", ":default")
               ->where("pg.id <> :priceGroupId")
               ->setParameter('default', 'false')
               ->setParameter('priceGroupId', $priceGroupId)
               ->getQuery();
        $numUpdated = $q->execute();

        return $numUpdated;
    }
}
