<?php

namespace Core\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function createUser(User $user)
    {
        if ($user) {
            $em =  $this->getEntityManager();
            $priceGroup = $em->getRepository('CoreUserBundle:PriceGroup')->findOneBy(array("default" => true));
            if ($priceGroup) {
                $user->setPriceGroup($priceGroup);
            }
            $em->persist($user);
            $em->flush();
        }

        return $user;
    }
}
