site_contact:
    pattern:  /{_locale}/contact
    defaults: { _controller: SiteMarketingBundle:Contact:contact, _locale: %locale% }

site_contact_form_send:
    pattern:  /{_locale}/contact/send
    defaults: { _controller: SiteMarketingBundle:Contact:sendContactForm, _locale: %locale% }
    requirements:
        _method: post

site_contact_multi_form_send:
    pattern:  /{_locale}/contactmulti/send
    defaults: { _controller: SiteMarketingBundle:Contact:sendContactMultiForm, _locale: %locale% }
    requirements:
        _method: post

site_contact_claim_form_send:
    pattern:  /{_locale}/contactclaim/send
    defaults: { _controller: SiteMarketingBundle:Contact:sendContactClaimForm, _locale: %locale% }
    requirements:
        _method: post
