parameters:
#    site_marketing.example.class: Site\MarketingBundle\Example

services:
#    site_marketing.example:
#        class: %site_marketing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
