parameters:
#    core_content.example.class: Core\ContentBundle\Example

services:
#    core_content.example:
#        class: %core_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
