parameters:
#    site_newsletter.example.class: Site\NewsletterBundle\Example

services:
#    site_newsletter.example:
#        class: %site_newsletter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
