parameters:
#    site_product.example.class: Site\ProductBundle\Example

services:
#    site_product.example:
#        class: %site_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
