parameters:
#    core_price.example.class: Core\PriceBundle\Example

services:
#    core_price.example:
#        class: %core_price.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
