parameters:
#    core_newsletter.example.class: Core\NewsletterBundle\Example

services:
#    core_newsletter.example:
#        class: %core_newsletter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
