parameters:
#    site_category.example.class: Site\CategoryBundle\Example

services:
#    site_category.example:
#        class: %site_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
