<?php

namespace Core\UserTextBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTextRepository extends EntityRepository
{
    public function setHint(\Doctrine\ORM\Query $query)
    {
        return $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
    }

    public function getByName($name)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select("ut")
            ->from("CoreUserTextBundle:UserText", "ut")
            ->andWhere("ut.name = :name")
            ->setParameter('name', $name)
            ->getQuery();

        return $this->setHint($query)->getOneOrNullResult();
    }

    public function getUserText($name, $create = false)
    {

        $entity = $this->getByName($name);
        if ($entity === null && $create) {
             $entity  = new UserText();
             $entity->setName($name);
             $this->getEntityManager()->persist($entity);
             $this->getEntityManager()->flush();
        }

        return $entity;
    }
}
