parameters:
#    site_shop.example.class: Site\ShopBundle\Example

services:
#    site_shop.example:
#        class: %site_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
