parameters:
#    site_banner.example.class: Site\BannerBundle\Example

services:
#    site_banner.example:
#        class: %site_banner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
