content_media:
    pattern:  /{category}
    defaults: { _controller: "CoreContentBundle:Media:index", category: ~}
    requirements:
        category: \d+

content_media_new:
    pattern:  /new/{type}/{category}
    defaults: { _controller: "CoreContentBundle:Media:new", category: ~ }

content_media_create:
    pattern:  /create/{type}/{category}
    defaults: { _controller: "CoreContentBundle:Media:create", category: ~ }
    requirements: { _method: post }

content_media_edit:
    pattern:  /{id}/edit/{type}/{category}
    defaults: { _controller: "CoreContentBundle:Media:edit", category: ~ }

content_media_update:
    pattern:  /{id}/update/{type}/{category}
    defaults: { _controller: "CoreContentBundle:Media:update", category: ~ }
    requirements: { _method: post }

content_media_delete:
    pattern:  /{id}/delete/{type}/{category}
    defaults: { _controller: "CoreContentBundle:Media:delete", category: ~ }
    requirements: { _method: post }

content_media_up:
    pattern:  /{id}/moveup/{position}/{category}
    defaults: { _controller: "CoreContentBundle:Media:moveUp", category: ~  }

content_media_down:
    pattern:  /{id}/movedown/{position}/{category}
    defaults: { _controller: "CoreContentBundle:Media:moveDown", category: ~  }

content_media_position:
    pattern:  /{id}/position/{category}
    defaults: { _controller: "CoreContentBundle:Media:position", category: ~  }

content_media_position_update:
    pattern:  /{id}/positionupdate/{category}
    defaults: { _controller: "CoreContentBundle:Media:positionUpdate", category: ~  }
    requirements: { _method: post }
