parameters:
#    site_default.example.class: Site\DefaultBundle\Example

services:
#    site_default.example:
#        class: %site_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
