<?php

namespace Core\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends EntityRepository
{
    public function updateDefaultPrice($productId, $priceId)
    {
        $q = $this->getEntityManager()->createQueryBuilder()
               ->update("CoreProductBundle:Price", "p")
               ->set("p.default", ":default")
               ->where("p.id <> :priceId")
               ->andWhere("p.product = :productId")
               ->setParameter('default', 'false')
               ->setParameter('priceId', $priceId)
               ->setParameter('productId', $productId)
               ->getQuery();
        $numUpdated = $q->execute();

        return $numUpdated;
    }
}
