groupon:
    pattern:  /
    defaults: { _controller: "CoreProductBundle:Groupon:index" }

groupon_show:
    pattern:  /{id}/show
    defaults: { _controller: "CoreProductBundle:Groupon:show" }

groupon_new:
    pattern:  /new
    defaults: { _controller: "CoreProductBundle:Groupon:new" }

groupon_create:
    pattern:  /create
    defaults: { _controller: "CoreProductBundle:Groupon:create" }
    requirements: { _method: post }

groupon_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CoreProductBundle:Groupon:edit" }

groupon_update:
    pattern:  /{id}/update
    defaults: { _controller: "CoreProductBundle:Groupon:update" }
    requirements: { _method: post|put }

groupon_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CoreProductBundle:Groupon:delete" }
    requirements: { _method: post|delete }
