parameters:
#    core_media.example.class: Core\MediaBundle\Example

services:
#    core_media.example:
#        class: %core_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
