<?php

namespace Core\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Core\UserBundle\Entity\User;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function getUserAddressQueryBuilder($userId = null)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                    ->select("a")
                    ->from('CoreShopBundle:Address', "a")
                    ->addOrderBy('a.name', 'ASC')
                    ->addOrderBy('a.id', 'ASC');
        if ($userId !== null) {
            $queryBuilder->andWhere("a.user = :uid")
            ->setParameter('uid', $userId);
        }

        return $queryBuilder;
    }

    public function createUser(User $user, $addresses = array())
    {
        if ($user && !empty($addresses)) {
            $em = $this->getEntityManager();
            foreach ($addresses as $addr) {
                if (!empty($addr)) {
                    $addr->setUser($user);
                    $em->persist($addr);
                }
            }
            $em->persist($user);
            $em->flush();
        }
    }
}
