<?php

namespace Core\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends EntityRepository
{
    public function getProductsOrderCount($entities) 
    {
        $querybuilder = $this->createQueryBuilder('oi')
            ->select("sum(oi.amount) as amount, p.id as product_id")
            ->join("oi.product", "p");
        if ($entities != null) {
            $expr = $querybuilder->expr()->in("oi.product", $entities);
            $querybuilder->andWhere($expr);
        }

        $query = $querybuilder->getQuery();
        
        $result = array();
        foreach ($query->itareate() as $key => $row) {
            $entity = $row[$key];
            $result[$entity['product_id']] = $entity;
        }
        
        return $result;
    }
}
