<?php

namespace Core\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function setHint(\Doctrine\ORM\Query $query)
    {
        return $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
    }

    public function getPaymentQueryBuilder($enabled = false)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select("p, c")
            ->from("CoreShopBundle:Payment", "p")
            ->leftJoin("p.currency", "c")
            ->orderBy('p.name', 'ASC');
        if ($enabled) {
            $queryBuilder->andWhere('p.enabled =:enabled')
            ->setParameter('enabled', $enabled);
        }

        return $queryBuilder;
    }
}
