parameters:
#    core_marketing.example.class: Core\MarketingBundle\Example

services:
#    core_marketing.example:
#        class: %core_marketing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
