<?php

namespace Core\PriceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * currencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    public function updateDefaultCurrency($exlude)
    {
       $q = $this->getEntityManager()->createQueryBuilder()
               ->update("CorePriceBundle:Currency", "c")
               ->set("c.default", ':default')
               ->where("c.id <> :id")
               ->setParameter('default', 'false')
               ->setParameter('id', $exlude)
               ->getQuery();
       $numUpdated = $q->execute();

       return $numUpdated;
    }
}
