<?php

namespace Core\MarketingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getMessagesByTypeQueryBuilder($type = null)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
               ->select("m")
               ->from("CoreMarketingBundle:Message", "m")
               ->orderBy("m.createdAt", 'desc');
        if ($type !== null) {
            $queryBuilder ->andWhere("m.type = :type")
                ->setParameter('type', $type);
        }

       return $queryBuilder;
    }

    public function getMessagesByTypeQuery($type = null)
    {
        return $this->getMessagesByTypeQueryBuilder($type)->getQuery();
    }
}
