vat:
    pattern:  /
    defaults: { _controller: "CorePriceBundle:VAT:index" }

vat_show:
    pattern:  /{id}/show
    defaults: { _controller: "CorePriceBundle:VAT:show" }

vat_new:
    pattern:  /new
    defaults: { _controller: "CorePriceBundle:VAT:new" }

vat_create:
    pattern:  /create
    defaults: { _controller: "CorePriceBundle:VAT:create" }
    requirements: { _method: post }

vat_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CorePriceBundle:VAT:edit" }

vat_update:
    pattern:  /{id}/update
    defaults: { _controller: "CorePriceBundle:VAT:update" }
    requirements: { _method: post|put }

vat_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CorePriceBundle:VAT:delete" }
    requirements: { _method: post|delete }
