<?php

namespace Core\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterGroupRepository extends EntityRepository
{
}
